coord_output: true
mask_output: true
glyph_coord_output: true
glyph_mask_output: true

vertical: false
quality: [70, 99]
visibility_check: true

corpus:
  weights: [1]
  args:
    # length augmentable corpus
    - paths: [resources/corpus/kz_corpus_generated.txt]
      weights: [1]
      min_length: 1
      max_length: 25

font:
  paths: [resources/kz_fonts]
  weights: [1]
  size: [10, 80]
  bold: 0

texture:
  prob: 0.5
  args:
    paths: [resources/image]
    weights: [1]
    alpha: [0, 1]
    grayscale: 0
    crop: 1

colormap2:
  paths: [resources/colormap/iiit5k_gray.txt]
  weights: [1]
  k: 2
  alpha: [1, 1]
  colorize: 1

colormap3:
  paths: [resources/colormap/iiit5k_gray.txt]
  weights: [1]
  k: 3
  alpha: [1, 1]
  colorize: 1

color:
  gray: [0, 255]
  alpha: [1, 1]
  colorize: 1

shape:
  prob: 1
  args:
    weights: [1, 1]
    args:
      # elastic distortion
      - alpha: [15, 25]
        sigma: [12, 15]
      # elastic distortion
      - alpha: [1, 2]
        sigma: [0.5, 1]

layout:
  weights: [4, 1]
  args:
    # flow layout
    - space: [-1, 4]
      line_align: [middle]
    # curve layout
    - curve: [5, 20]
      space: [-1, 4]
      convex: 0.5
      upward: 0.5

style:
  prob: 0.1
  args:
    weights: [1]
    args:
      # text border
      - size: [1, 12]
        alpha: [1, 1]
        grayscale: 0

transform:
  prob: 1
  args:
    weights: [1, 1, 1, 1, 1, 1, 2]
    args:
      # perspective x
      - percents: [[0.5, 1], [1, 1]]
        aligns: [[0, 0], [0, 0]]
      # perspective y
      - percents: [[1, 1], [0.5, 1]]
        aligns: [[0, 0], [0, 0]]
      # trapezoidate x
      - weights: [1, 0, 1, 0]
        percent: [0.75, 1]
        align: [-1, 1]
      # trapezoidate y
      - weights: [0, 1, 0, 1]
        percent: [0.5, 1]
        align: [-1, 1]
      # skew x
      - weights: [1, 0]
        angle: [0, 30]
        ccw: 0.5
      # skew y
      - weights: [0, 1]
        angle: [0, 10]
        ccw: 0.5
      # rotate
      - angle: [0, 10]
        ccw: 0.5

pad:
  prob: 1
  args:
    pxs: [[0, 10], [0, 10], [0, 10], [0, 10]]

postprocess:
  args:
    # gaussian noise
    - prob: 1
      args:
        scale: [4, 8]
        per_channel: 0
    # gaussian blur
    - prob: 0.9
      args:
        sigma: [0, 2]
    # resample
    - prob: 0.1
      args:
        size: [0.4, 0.4]
    # median blur
    - prob: 1
      args:
        k: [1, 1]
